language: bash

services:
  - docker

before_script:
  - git clone https://github.com/kward/shunit2.git

before_install:
  - docker build --tag jcardarelli/venv-ansible .
  - docker run --rm jcardarelli/venv-ansible /bin/bash -c "source /root/.virtualenvs/ansible/bin/activate && ansible --version"

after_install:
  - docker rm jcardarelli/venv-ansible
  - docker rmi jcardarelli/venv-ansible

script:
  - bash tests/equality.sh
