language: bash
env:
  - REPONAME=venv-ansible

services:
  - docker

before_script:
  - git clone https://github.com/kward/shunit2.git

before_install:
  - docker build --tag $REPONAME .
  - docker run --rm $REPONAME /bin/bash -c "source /root/.virtualenvs/ansible/bin/activate && ansible --version"

after_install:
  - docker rm $REPONAME
  - docker rmi $REPONAME

script:
  - bash tests/equality.sh
